# Generated by Django 4.2.3 on 2023-07-26 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('year_released', models.IntegerField()),
                ('date_of_statehood', models.IntegerField()),
            ],
        ),
    ]
