# Generated by Django 4.2.3 on 2023-07-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('year_released', models.IntegerField()),
                ('date_of_statehood', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Minting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date added to this collection')),
                ('mint_mark', models.CharField(choices=[('D', 'Denver'), ('P', 'Philadelphia'), ('S', 'San Francisco')], default='D', max_length=1)),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.coin')),
            ],
        ),
    ]
